# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_geo', models.BooleanField(default=False, verbose_name='isGEO')),
                ('is_geo_impl', models.BooleanField(default=False, verbose_name='isGEOImpl')),
                ('query_type', models.CharField(choices=[('NAV', 'Navigational (eg www.facebook.com)'), ('IDC', 'Informational - Directed - Closed (Learn about topic; single answer)'), ('IDO', 'Informational - Directed - Open (Learn about topic; unconstrained depth)'), ('IUN', 'Informational - Undirected (tell me about; learn everything/anything about topic)'), ('IAD', 'Informational Advice'), ('ILO', 'Informational Locate'), ('ILI', 'Informational List'), ('RDO', 'Resource Download'), ('RDE', 'Resource Entertainment'), ('RIN', 'Resource Interact'), ('ROB', 'Resource Obtain')], default='NAV', max_length=2, verbose_name='Query Type')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='query',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotate.Query'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
