# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_geo', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='1. Is this query best answered with a pin on a map?')),
                ('is_geo_expl', models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='2. Is the location explicit in the query?')),
                ('query_type', models.CharField(choices=[('NAV', 'Navigational'), ('IDC', 'Directed - Closed'), ('IDO', 'Directed - Open'), ('IUN', 'Undirected'), ('IAD', 'Advice'), ('ILO', 'Locate'), ('ILI', 'List'), ('RDO', 'Download'), ('RDE', 'Entertainment'), ('RIN', 'Interact'), ('ROB', 'Obtain')], default=None, max_length=3, verbose_name='3. What type of query is this?')),
            ],
        ),
        migrations.CreateModel(
            name='HtmlMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'queries',
            },
        ),
        migrations.CreateModel(
            name='Skipped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='annotate.Annotation')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='annotate.Query')),
                ('skipped', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='annotate.Skipped')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set([('query', 'user')]),
        ),
    ]
