# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='is_geo_expl',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='2. Is the location explicit in the query?'),
        ),
    ]
