# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0002_auto_20160905_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='query_type',
            field=models.CharField(choices=[('NAV', 'Navigational (eg www.facebook.com)'), ('IDC', 'Informational - Directed - Closed (Learn about topic; single answer)'), ('IDO', 'Informational - Directed - Open (Learn about topic; unconstrained depth)'), ('IUN', 'Informational - Undirected (tell me about; learn everything/anything about topic)'), ('IAD', 'Informational Advice'), ('ILO', 'Informational Locate'), ('ILI', 'Informational List'), ('RDO', 'Resource Download'), ('RDE', 'Resource Entertainment'), ('RIN', 'Resource Interact'), ('ROB', 'Resource Obtain')], default='NAV', max_length=3, verbose_name='Query Type'),
        ),
    ]
