# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0003_auto_20170525_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='is_geo_expl',
        ),
        migrations.AddField(
            model_name='annotation',
            name='loc_type',
            field=models.CharField(choices=[('NAV', 'Web Navigation'), ('IDC', 'Directed - Closed'), ('IDO', 'Directed - Open'), ('IUN', 'Undirected'), ('IAD', 'Advice'), ('ILO', 'Locate'), ('ILI', 'List'), ('RDO', 'Download'), ('RDE', 'Entertainment'), ('RIN', 'Interact'), ('ROB', 'Obtain')], default=None, max_length=3, verbose_name='2. Is a location explicit in the query?'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='query_type',
            field=models.CharField(choices=[('YY', 'Yes -- with place name'), ('YN', 'Yes -- without place name'), ('NY', 'No'), ('NN', 'Not applicable')], default=None, max_length=3, verbose_name='3. What type of query is this?'),
        ),
    ]
