# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0004_auto_20170605_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='collection',
            field=models.CharField(default='pilot', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_geo',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='This questions asks whether this query would be most suitably answered by a spatial interface, such as a map or route directions. It could be presented using one or multiple pins, lines and/or regions, or a set of instructions', verbose_name='1. Is this query best answered with a pin on a map?'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='loc_type',
            field=models.CharField(choices=[('YY', 'Yes -- with place name'), ('YN', 'Yes -- without place name'), ('NY', 'No'), ('NN', 'Not applicable')], default=None, help_text='This questions asks whether this query contains a place name or other location reference (e.g., work) relating to Question 1.', max_length=3, verbose_name='2. Is a location explicit in the query?'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='query_type',
            field=models.CharField(choices=[('NAV', 'Web Navigation'), ('IDC', 'Directed - Closed'), ('IDO', 'Directed - Open'), ('IUN', 'Undirected'), ('IAD', 'Advice'), ('ILO', 'Locate'), ('ILI', 'List'), ('RDO', 'Download'), ('RDE', 'Entertainment'), ('RIN', 'Interact'), ('ROB', 'Obtain')], default=None, help_text='This questions asks you to classify the query into one of the subcategories of Navigation, Informational and Resource (Rose and Levinson, 2004). Below are the definitions as provided by Rose and Levinson, and examples for each of the categories. ', max_length=3, verbose_name='3. What type of query is this?'),
        ),
    ]
