# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0006_pilotquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round1Query',
            fields=[
            ],
            options={
                'verbose_name_plural': 'round 1 queries',
                'proxy': True,
                'indexes': [],
            },
            bases=('annotate.query',),
        ),
    ]
