# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0008_auto_20160907_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_annotations', to='annotate.Query')),
            ],
        ),
    ]
