# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotate', '0009_skippedannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='skippedannotation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skipped_annotations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
