# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0010_skippedannotation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='is_geo',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='isGEO'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_geo_impl',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='isGEOImpl'),
        ),
    ]
