# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0013_auto_20160908_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='is_geo',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='Is GEO?'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_geo_impl',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='Is GEO implied?'),
        ),
    ]
