# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0016_auto_20160908_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='is_geo',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='Is GEO?'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='query_type',
            field=models.CharField(choices=[('', 'please select'), ('NAV', 'Navigational (eg www.facebook.com)'), ('IDC', 'Informational - Directed - Closed (Learn about topic; single answer)'), ('IDO', 'Informational - Directed - Open (Learn about topic; unconstrained depth)'), ('IUN', 'Informational - Undirected (tell me about; learn everything/anything about topic)'), ('IAD', 'Informational Advice'), ('ILO', 'Informational Locate'), ('ILI', 'Informational List'), ('RDO', 'Resource Download'), ('RDE', 'Resource Entertainment'), ('RIN', 'Resource Interact'), ('ROB', 'Resource Obtain')], max_length=3, verbose_name='Query Type'),
        ),
    ]
