# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotate', '0017_auto_20160908_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_geo',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='1. Can this query be answered with a pin on a map?'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='is_geo_impl',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None, verbose_name='2. Is the location implicit in the query?'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='query_type',
            field=models.CharField(choices=[('NAV', 'Navigational (eg www.facebook.com)'), ('IDC', 'Informational - Directed - Closed'), ('IDO', 'Informational - Directed - Open'), ('IUN', 'Informational - Undirected'), ('IAD', 'Informational Advice'), ('ILO', 'Informational Locate'), ('ILI', 'Informational List'), ('RDO', 'Resource Download'), ('RDE', 'Resource Entertainment'), ('RIN', 'Resource Interact'), ('ROB', 'Resource Obtain')], default=None, max_length=3, verbose_name='3. What type of query is this?'),
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='skippedannotation',
            unique_together=set([('query', 'user')]),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='annotation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='annotate.Annotation'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='annotate.Query'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='query',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set([('query', 'user')]),
        ),
    ]
