# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0018_auto_20161009_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('html', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='skippedannotation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='skippedannotation',
            name='query',
        ),
        migrations.RemoveField(
            model_name='skippedannotation',
            name='user',
        ),
        migrations.DeleteModel(
            name='SkippedAnnotation',
        ),
    ]
